config/routes.rb
Rails.application.routes.draw do
  resources :book_reviews
  get 'users/show'
  resources :comments
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    has_many :book_review, -> { order "created_at DESC"}
end

app/models/book_review.rb
class BookReview < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_one_attached :avatar

  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
     devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
    end    
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  before_action :set_book_review, only: [:show, :edit, :update, :destroy]

  # GET /book_reviews
  # GET /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1
  # GET /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews
  # POST /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)
    @book_review.user_id = current_user.id

    respond_to do |format|
      if @book_review.save
        url = "/books/" + @book_review.book_id.to_s
        format.html { redirect_to url, notice: 'Book review was successfully created.' }
        # format.html { redirect_to @book_review, notice: 'Book review was successfully created.' }
        format.html { redirect_to @book_review, notice: 'Book review was successfully created.' }
        format.json { render :show, status: :created, location: @book_review }
      else
        format.html { render :new }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reviews/1
  # PATCH/PUT /book_reviews/1.json
  def update
    respond_to do |format|
      if @book_review.update(book_review_params)
        format.html { redirect_to @book_review, notice: 'Book review was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_review }
      else
        format.html { render :edit }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reviews/1
  # DELETE /book_reviews/1.json
  def destroy
    @book_review.destroy
    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: 'Book review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_review
      @book_review = BookReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_review_params
      params.require(:book_review).permit(:user_id, :book_id, :review)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
      @book_review = BookReview.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages, :image, :detail)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
       @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_reviews/_form.html.erb
<%= form_with(model: book_review, local: true) do |form| %>
  <% if book_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
        <% book_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing Book Review</h1>

<%= render 'form', book_review: @book_review %>

<%= link_to 'Show', @book_review %> |
<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_reviews.each do |book_review| %>
      <tr>
        <td><%= book_review.user_id %></td>
        <td><%= book_review.book_id %></td>
        <td><%= book_review.review %></td>
        <td><%= link_to 'Show', book_review %></td>
        <td><%= link_to 'Edit', edit_book_review_path(book_review) %></td>
        <td><%= link_to 'Destroy', book_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Review', new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New Book Review</h1>

<%= render 'form', book_review: @book_review %>

<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @book_review.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_review.book_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @book_review.review %>
</p>

<%= link_to 'Edit', edit_book_review_path(@book_review) %> |
<%= link_to 'Back', book_reviews_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :number_of_pages %>
    <%= form.number_field :number_of_pages %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Number of pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @book.detail %>
</p>

<p>
   <% if @book.image.attached? %>
     <%= image_tag @book.image %>
   <% end %>
 </p>

<p>Review From</p>
 <%= form_with(model: @book_review, local: true) do |form| %>
   <div class= "field">
     <%= form.text_area :review %>
     <%= form.hidden_field :book_id, :value => @book.id %>
   </div>
   <div class="actions">
     <%= form.submit %>
   </div>
 <% end %>

<p>Review List</p>
  <ul>
    <% @book.book_review.each do |book_review|%>
      <li><%= book_review.review %>
      (<i><%= book_review.user.name %></i>)</li>
    <% end %>
  </ul>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thefirstrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "ホーム", root_path %>
    <br>
    <br>
    
    <% if user_signed_in? %>
        <p>こんにちわ, <%= link_to current_user.email , users_show_path %> </p>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "サインイン", new_user_session_path %>
        <%= link_to "ユーザ登録", new_user_registration_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<hr>
<h1>ホームページ</h1>

<br>
<%= link_to "本一覧をみる", books_path %>

app/views/users/show.html.erb
<hr>
<h1>プロフィール</h1>

<p>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar %>
  <% end %>
</p>

<h3>名前</h3>
<%= @user.name %>

<h3>年齢</h3>
<%= @user.age %>

<h3>メールアドレス</h3>
<%= @user.email %> 